### ISSUE TITLE
Usage within ansible?

### ISSUE THREAD

**Issue by memelet** [mtchavez/consul-ansible-module#44]
How to pull this module into ansible? I see its not in galaxy and the directory structure does not look like anything that can be requirements.txt'ed via git. Am I missing something simple?

**Comment by mtchavez** [comment]
Yeah this is an module within Ansible not a role. See more on modules [here](http://docs.ansible.com/ansible/modules.html). With the Ansible 2.0 release there will be a minimal consul module in the core modules.
